all: test

test:
	@dune exec -- ./leffect.exe -s source.wav -t target.wav --play

muff:
	./leffect -s ../Automated-GuitarAmpModelling/Data/test/muff-input.wav -t ../Automated-GuitarAmpModelling/Data/test/muff-target.wav
